import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css';
import MainHeader from '@/Components/Header/MainHeader';
const inter = Inter({ subsets: ['latin'] })
import Particle from '@/Components/Particle';
import { Suspense } from 'react';
import Footer from '@/Components/footer/Footer';
import Loading from '@/Components/Loading';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      
      <body className={inter.className }>
        
      <nav>
        <Particle/>
        <MainHeader/>
      </nav>
    <Suspense fallback={<Loading/>}>
        {children}
        </Suspense>
      
      <footer>
        <Footer/>
      </footer>
     
       
     
        </body>

    </html>
  )
}
